server:
  port: 8090

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:piedrazul;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PiedraAzul_Realm

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-para-cambio-obligatorio-en-prod-2026}
    expiration-minutes: ${JWT_EXP_MIN:120}

keycloak:
  admin:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:PiedraAzul_Realm}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:PiedraAzul_Postman}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:TwLCFJauVgZLnaV2YRB3kHRwvuQaUFXc}
