name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Keycloak
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_KEYCLOAK }}
      
      - name: Deploy Backend
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACK }}
      
      - name: Deploy Frontend
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONT }}